#spring:
#  data:
#    mongodb:
#      uri: 
#      database: journaldb
#      auto-index-creation : true
#
#server:
#  port: 8080
#  servlet:
#    context-path: /journal

spring:
  profiles:
    active: dev

logging:
  level:
    com:
      journal:
        journalApp :
          Services:
            UserService: DEBUG
